"""PDF 5: F1 2026 Glossary -- Technical, sporting, tire, and slang terms."""

import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from f1_pdf_style import F1PDF


def generate():
    pdf = F1PDF(
        title="2026 Glossary",
        subtitle="Terminology & Abbreviations"
    )
    pdf.add_cover_page()
    pdf.add_page()

    # -- Technical Terms ---------------------------------------------------
    pdf.section_header("Technical Terms")
    pdf.body_text(
        "Key engineering and design terminology used in Formula 1."
    )

    technical = [
        ("Active Aerodynamics",
         "Movable aerodynamic elements (front and rear wings) that adjust angle "
         "in real time. New for 2026, replacing DRS with a broader system that "
         "works on straights (X-mode) and through corners."),
        ("Bargeboard",
         "Complex aerodynamic surfaces mounted between the front wheels and "
         "sidepods. Largely eliminated under 2022+ ground-effect regulations."),
        ("Brake-by-Wire",
         "Electronic braking system on the rear axle that blends mechanical "
         "braking with energy recovery (MGU-K regeneration)."),
        ("Diffuser",
         "Aerodynamic device at the rear underside of the car that accelerates "
         "airflow to create low pressure and downforce. 2026 cars use a larger "
         "diffuser with a flat floor instead of Venturi tunnels."),
        ("Drag Reduction System (DRS)",
         "Adjustable rear wing flap used 2011-2025. Eliminated for 2026 and "
         "replaced by active aerodynamics (X-mode)."),
        ("Energy Recovery System (ERS)",
         "System that recovers kinetic and heat energy. In 2026, the MGU-K "
         "produces up to 350 kW (up from 120 kW), providing roughly 50% of "
         "total power output."),
        ("Flat Floor",
         "2026 cars use a flat underbody instead of shaped Venturi tunnels, "
         "paired with a larger diffuser to generate ground-effect downforce."),
        ("Ground Effect",
         "Aerodynamic downforce generated by shaping the airflow beneath the "
         "car. The low-pressure zone under the floor sucks the car toward the "
         "track surface."),
        ("MGU-K (Motor Generator Unit - Kinetic)",
         "Electric motor/generator connected to the drivetrain. Harvests "
         "braking energy and deploys it as additional power. Output increases "
         "to 350 kW for 2026."),
        ("MGU-H (Motor Generator Unit - Heat)",
         "Electric motor/generator connected to the turbocharger. Harvested "
         "exhaust heat energy. Eliminated from the 2026 power unit regulations."),
        ("Monocoque",
         "The carbon fiber survival cell that forms the core structure of an "
         "F1 car, housing the driver and serving as the main chassis."),
        ("Power Unit (PU)",
         "The complete powertrain comprising ICE (internal combustion engine), "
         "turbocharger, MGU-K, energy store (battery), and control electronics. "
         "2026 PUs run on 100% sustainable fuel."),
        ("Sustainable Fuel",
         "100% advanced sustainable fuel is mandatory for 2026. Must be a "
         "drop-in replacement with the same energy density requirements."),
        ("Venturi Tunnel",
         "Shaped channels in the car's floor that accelerate airflow to "
         "generate downforce. Used 2022-2025; replaced by flat floor for 2026."),
        ("X-Mode",
         "The active aero mode for 2026 that opens wing elements on straights "
         "to reduce drag, functioning similarly to DRS but on both front and "
         "rear wings simultaneously."),
    ]

    for term, definition in technical:
        pdf.glossary_entry(term, definition)

    # -- Sporting Terms ----------------------------------------------------
    pdf.section_header("Sporting Terms")
    pdf.body_text(
        "Rules, flags, and procedures that govern how races are run."
    )

    sporting = [
        ("107% Rule",
         "In Q1, any driver failing to lap within 107% of the fastest time "
         "may be excluded from starting the race at the stewards' discretion."),
        ("Black and Orange Flag",
         "Mechanical flag - shown to a specific car requiring it to pit for "
         "repairs due to a dangerous mechanical issue."),
        ("Blue Flag",
         "Shown to a driver about to be lapped, requiring them to let the "
         "faster car through within three flag points."),
        ("Formation Lap",
         "The lap before the race start where cars follow the pole-sitter "
         "around the circuit to warm tires and brakes before taking their "
         "grid positions."),
        ("Grid Penalty",
         "A penalty applied before the race that moves a driver further back "
         "on the starting grid (e.g., for engine changes, gearbox changes, "
         "or impeding in qualifying)."),
        ("Parc Ferme",
         "Restricted conditions under which cars may not be substantially "
         "modified. Applies from the start of qualifying until the race."),
        ("Safety Car (SC)",
         "Deployed when conditions are too dangerous for racing but not severe "
         "enough for a red flag. The field bunches up behind the safety car."),
        ("Virtual Safety Car (VSC)",
         "A caution period where all cars must reduce speed by ~40% using "
         "delta times, without a physical safety car on track."),
        ("Red Flag",
         "Race suspension. All cars return to the pit lane. The race may "
         "be restarted, resumed, or declared."),
        ("Stewards",
         "The officials who enforce the sporting regulations, investigate "
         "incidents, and issue penalties during a race weekend."),
        ("Drive-Through Penalty",
         "Driver must enter the pit lane and drive through at the speed "
         "limit without stopping, then rejoin the race."),
        ("Stop-and-Go Penalty",
         "Driver must pit and remain stationary for a specified time (usually "
         "10 seconds) before rejoining. The most severe in-race penalty."),
        ("Time Penalty",
         "Added to a driver's race time (5s, 10s, or 20s). Can be served "
         "at the next pit stop or added to final classification."),
        ("Super License",
         "The FIA license required to compete in Formula 1. Earned through "
         "points accumulated in junior racing series."),
    ]

    for term, definition in sporting:
        pdf.glossary_entry(term, definition)

    # -- Tire Terms --------------------------------------------------------
    pdf.section_header("Tire Terms")
    pdf.body_text(
        "Terminology related to Pirelli's tire compounds and behavior."
    )

    tire_terms = [
        ("Blistering",
         "Overheating of the tire surface causing bubbles or chunks of "
         "rubber to separate. Reduces grip and accelerates degradation."),
        ("Compound",
         "The specific rubber mixture of a tire. Pirelli supplies five dry "
         "compounds (C1-C5, hardest to softest); three are selected per race."),
        ("Degradation (Deg)",
         "The gradual loss of tire performance over a stint. Measured in "
         "seconds per lap of pace loss."),
        ("Flat Spot",
         "A worn area on a tire caused by locking a wheel under braking. "
         "Creates vibration and may require an unplanned pit stop."),
        ("Graining",
         "Small pieces of rubber roll up on the tire surface when the tire "
         "isn't in its optimal temperature window. Usually clears itself "
         "as the tire warms up."),
        ("Marbles",
         "Small balls of discarded rubber that accumulate off the racing "
         "line. Driving over marbles significantly reduces grip."),
        ("Pit Window",
         "The optimal lap range for a pit stop based on tire strategy, "
         "track position, and competitor strategies."),
        ("Tire Blankets",
         "Electric heaters wrapped around tires before fitting to bring "
         "them closer to operating temperature. Still permitted in 2026."),
        ("Undercut",
         "Pitting earlier than a rival to benefit from fresh tires on a "
         "clear track, gaining time to emerge ahead after they pit."),
        ("Overcut",
         "Staying out longer than a rival on older tires, hoping the pit "
         "stop delta and traffic work in your favor."),
    ]

    for term, definition in tire_terms:
        pdf.glossary_entry(term, definition)

    # -- Slang & Jargon ----------------------------------------------------
    pdf.section_header("Slang & Jargon")
    pdf.body_text(
        "Informal terms you'll hear from commentators, drivers, and fans."
    )

    slang = [
        ('"Box, box"',
         "Radio call from the pit wall telling a driver to come into the "
         'pits. "Box" comes from the German word "Boxenstopp" (pit stop).'),
        ("Dirty Air",
         "Turbulent, low-energy air behind a car. Reduces downforce for "
         "a following car, making overtaking difficult. 2026 rules aim to "
         "reduce this effect."),
        ("Purple Sector",
         "The fastest sector time set by any driver during a session. "
         "Displayed in purple on the timing screens."),
        ("Green Sector",
         "A personal-best sector time for that driver in the session."),
        ("Yellow Sector",
         "A sector time slower than the driver's personal best."),
        ("Mega Lap",
         "Slang for an exceptionally fast qualifying or race lap."),
        ("Get In There!",
         "Common celebratory radio message from a race engineer after a "
         "win or strong result."),
        ("Lights Out",
         "The moment the five red lights extinguish to start the race."),
        ("Porpoising",
         "Bouncing caused by inconsistent ground-effect aerodynamics. The "
         "car oscillates as downforce is gained and lost at high speed."),
        ("Tow / Slipstream",
         "Driving in the low-drag wake of another car to gain a straight-line "
         "speed advantage. Useful in qualifying and on long straights."),
        ("Train",
         "A line of cars running closely together, unable to overtake. "
         "Often seen at circuits with limited passing opportunities."),
    ]

    for term, definition in slang:
        pdf.glossary_entry(term, definition)

    # -- Abbreviations -----------------------------------------------------
    pdf.section_header("Common Abbreviations")

    abbreviations = [
        ["DFL", "Did Not Finish (Last)", "DNF", "Did Not Finish"],
        ["DNS", "Did Not Start", "DSQ", "Disqualified"],
        ["ERS", "Energy Recovery System", "FIA", "Fed. Int'le de l'Automobile"],
        ["FL", "Fastest Lap", "FP1/2/3", "Free Practice 1/2/3"],
        ["ICE", "Internal Combustion Engine", "MGU-K", "Motor Generator Unit-Kinetic"],
        ["PU", "Power Unit", "SC", "Safety Car"],
        ["SQ", "Sprint Qualifying", "VSC", "Virtual Safety Car"],
        ["WDC", "World Drivers' Championship", "WCC", "World Constructors' Champ."],
    ]

    pdf.styled_table(
        headers=["Abbr.", "Meaning", "Abbr.", "Meaning"],
        data=abbreviations,
        col_widths=[20, 68, 20, 68],
        font_size=9,
    )

    pdf.save("2026-Glossary.pdf")


if __name__ == "__main__":
    generate()
